- name: variables in files
  hosts: local
  connection: local
  vars:  
    TRAINER: girisha
  vars_files:
  - giri.yaml
  tasks:
  - name: "variables inside file"
    vars:
     COURSE: Ansible
    ansible.builtin.debug:
     msg: "course is {{ COURSE }}, Trainer is {{ TRAINER }}"
     #here it will print course : ansible taken from tasks variable as a priority and trainer is mentioned in 2 places inside course.yaml and play level variables here priority is from course.yaml

     #variables priority
     #
