- name: ansible command vs shell
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: checking command and shell 
    #ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output
  - name: printing command output
    ansible.builtin.debug:
      msg: " {{ users_output }} "

  - name: shell test
    ansible.builtin.shell: ls -ltr > files.txt
    register: files_output
  - name: printing shell test
    ansible.builtin.debug:
      msg: "printing {{ files_output }}"