- name : demo on filters
  hosts: local
  connection: local
  vars:
    topics: "linux, shell, ansible, terraform"
    #greeting: "good morning"
    tagsmap:
      name: ansible
      project: roboshop
      component: catalogue
    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greeting default variable
    ansible.builtin.debug:
      msg: "Hi girisha ,{{ greeting | default ('Good morning') }}"
  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"
  - name: converting map to list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}"
  - name: converting list to map
    ansible.builtin.debug:
      msg: "{{ tagslist | items2dict}}"



