- name: gathering facts 
  hosts: local
  connection: local
  tasks:
  - name: printing ansible facts
    ansible.builtin.debug:
      msg: "printing {{ ansible_facts }}"

  # - name: check redhat or not
  #   ansible.builtin.debug:
  #     msg: "yes package is redhat"
  #   when: ansible_facts.os.family == "redhat"

  # - name: check debian or not 
  #   ansible.builtin.debug:
  #     msg: "yes package manager is debian"
  #   when: ansible_facts.os.family == "debian"